import type { EasingPreset } from "@/types/easing";

export const BUILTIN_EASING_PRESETS: EasingPreset[] = [
  {
    id: "linear",
    name: "Linear",
    description: "Constant velocity with no acceleration.",
    category: "Utility",
    cssValue: "linear",
    bezier: null,
    personality: "Mechanical",
    recommendedUse: "Constant movement, loaders, marquees only",
    isCustom: false,
  },
  {
    id: "ease",
    name: "Ease",
    description: "Classic CSS ease — a balanced default curve.",
    category: "Standard",
    cssValue: "cubic-bezier(0.25, 0.1, 0.25, 1)",
    bezier: { x1: 0.25, y1: 0.1, x2: 0.25, y2: 1 },
    personality: "Neutral",
    recommendedUse: "General fallback when unsure",
    isCustom: false,
  },
  {
    id: "ease-out",
    name: "Ease Out",
    description: "Fast start, gentle settle — feels responsive.",
    category: "Standard",
    cssValue: "cubic-bezier(0, 0, 0.58, 1)",
    bezier: { x1: 0, y1: 0, x2: 0.58, y2: 1 },
    personality: "Responsive",
    recommendedUse: "UI response and entrances",
    isCustom: false,
  },
  {
    id: "ease-in-out",
    name: "Ease In Out",
    description: "Smooth acceleration and deceleration.",
    category: "Standard",
    cssValue: "cubic-bezier(0.42, 0, 0.58, 1)",
    bezier: { x1: 0.42, y1: 0, x2: 0.58, y2: 1 },
    personality: "Balanced",
    recommendedUse: "Moving elements already on screen",
    isCustom: false,
  },
  {
    id: "soft-reveal",
    name: "Soft Reveal",
    description: "Long, luxurious deceleration for premium reveals.",
    category: "Soft",
    cssValue: "cubic-bezier(0.16, 1, 0.3, 1)",
    bezier: { x1: 0.16, y1: 1, x2: 0.3, y2: 1 },
    personality: "Refined",
    recommendedUse: "Premium and editorial reveals",
    isCustom: false,
  },
  {
    id: "snappy",
    name: "Snappy",
    description: "Quick and decisive — built for product UI.",
    category: "Snappy",
    cssValue: "cubic-bezier(0.2, 0.8, 0.2, 1)",
    bezier: { x1: 0.2, y1: 0.8, x2: 0.2, y2: 1 },
    personality: "Efficient",
    recommendedUse: "Fast product UI motion",
    isCustom: false,
  },
  {
    id: "confident",
    name: "Confident",
    description: "Strong settle with brand-safe energy.",
    category: "Editorial",
    cssValue: "cubic-bezier(0.22, 1, 0.36, 1)",
    bezier: { x1: 0.22, y1: 1, x2: 0.36, y2: 1 },
    personality: "Assured",
    recommendedUse: "Brand-safe motion with a strong settle",
    isCustom: false,
  },
  {
    id: "expressive-out",
    name: "Expressive Out",
    description: "Playful overshoot on arrival.",
    category: "Overshoot",
    cssValue: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    bezier: { x1: 0.34, y1: 1.56, x2: 0.64, y2: 1 },
    personality: "Playful",
    recommendedUse: "Playful overshoot moments, not high-frequency UI",
    isCustom: false,
  },
  {
    id: "sharp-in-out",
    name: "Sharp In Out",
    description: "Punchy acceleration and deceleration.",
    category: "Editorial",
    cssValue: "cubic-bezier(0.76, 0, 0.24, 1)",
    bezier: { x1: 0.76, y1: 0, x2: 0.24, y2: 1 },
    personality: "Bold",
    recommendedUse: "Bold wipes, mask reveals, editorial transitions",
    isCustom: false,
  },
  {
    id: "calm",
    name: "Calm",
    description: "Slow, gentle deceleration for relaxed motion.",
    category: "Soft",
    cssValue: "cubic-bezier(0.33, 1, 0.68, 1)",
    bezier: { x1: 0.33, y1: 1, x2: 0.68, y2: 1 },
    personality: "Serene",
    recommendedUse: "Wellness, premium, slow brand motion",
    isCustom: false,
  },
];

export const DEFAULT_EASING_ID = "ease-out";
export const DEFAULT_ENTRANCE_EASING_ID = "ease-out";
export const DEFAULT_EXIT_EASING_ID = "ease-in-out";
export const DEFAULT_TRANSITION_EASING_ID = "ease-in-out";

export const builtinEasingPresetMap = Object.fromEntries(
  BUILTIN_EASING_PRESETS.map((preset) => [preset.id, preset]),
) as Record<string, EasingPreset>;
