import type { BlockCategory, MotionBlockDefinition } from "@/types";

const ALL_FORMAT_IDS = ["format-9-16", "format-1-1", "format-4-5", "format-16-9"];

export const blockCategories: { id: BlockCategory; label: string }[] = [
  { id: "intro", label: "Intro" },
  { id: "logo", label: "Logo" },
  { id: "product", label: "Product" },
  { id: "proof", label: "Proof" },
  { id: "cta", label: "CTA" },
];

export const motionBlockDefinitions: MotionBlockDefinition[] = [
  {
    id: "logo-reveal",
    name: "Logo Reveal",
    category: "intro",
    description: "Introduce the brand mark with a confident entrance.",
    defaultDuration: 90,
    defaultContent: {
      logoText: "SCATTER",
      tagline: "Motion made simple",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.35,
        mainRatio: 0.4,
        outRatio: 0.25,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "standard",
        stagger: 6,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["cut", "crossfade", "push", "mask-reveal"],
  },
  {
    id: "feature-announcement",
    name: "Feature Announcement",
    category: "product",
    description: "Highlight a product feature with headline, subhead, and screenshot.",
    defaultDuration: 120,
    defaultContent: {
      headline: "Introducing Scatter",
      subhead: "Build branded motion in minutes, not days.",
      logoText: "SCATTER",
      backgroundColor: "",
      accentColor: "",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.4,
        mainRatio: 0.45,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "standard",
        stagger: 8,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "push", "wipe", "mask-reveal", "scale-through"],
  },
  {
    id: "product-carousel",
    name: "Product Carousel",
    category: "product",
    description: "Cycle through product shots with smooth transitions.",
    defaultDuration: 150,
    defaultContent: {
      title: "Our products",
      itemOne: "Product A",
      itemTwo: "Product B",
      itemThree: "Product C",
    },
    defaultMotion: {
      phases: {
        in: "fade",
        main: "hold",
        out: "fade-out",
        inRatio: 0.2,
        mainRatio: 0.6,
        outRatio: 0.2,
      },
      controls: {
        slideSpeed: 1,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "push", "wipe", "frame-split"],
  },
  {
    id: "stat-card",
    name: "Stat Card",
    category: "proof",
    description: "Present a key metric with emphasis.",
    defaultDuration: 90,
    defaultContent: {
      value: "10x",
      label: "Faster production",
      supportingText: "From brief to export in minutes",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.25,
        mainRatio: 0.55,
        outRatio: 0.2,
      },
      controls: {
        direction: "up",
        intensity: "hero",
        speed: "standard",
        stagger: 8,
        emphasis: 1.1,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "push", "scale-through"],
  },
  {
    id: "cta-lockup",
    name: "CTA Lockup",
    category: "cta",
    description: "Close with a call to action and brand lockup.",
    defaultDuration: 90,
    defaultContent: {
      message: "Ready to ship branded motion?",
      cta: "Get started",
      url: "scatter.dev",
      logoText: "SCATTER",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.3,
        mainRatio: 0.55,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "calm",
        stagger: 7,
        buttonScale: 1,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["cut", "crossfade", "mask-reveal"],
  },
  {
    id: "editorial-statement",
    name: "Editorial Statement",
    category: "intro",
    description: "Single-message hook or transition on a void field with optional accent word.",
    defaultDuration: 90,
    defaultContent: {
      headline: "You can make serious money.",
      subhead: "",
      accentWord: "money",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.35,
        mainRatio: 0.45,
        outRatio: 0.2,
      },
      controls: {
        direction: "up",
        intensity: "hero",
        speed: "calm",
        stagger: 8,
        glowAccent: "true",
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["cut", "crossfade", "fade", "mask-reveal"],
  },
  {
    id: "big-stat-proof",
    name: "Big Stat Proof",
    category: "proof",
    description: "Centered proof line with an embedded stat and optional step rail.",
    defaultDuration: 90,
    defaultContent: {
      statValue: "50%",
      statWrapper: "You get {stat} of that revenue for the first year",
      stepLabel: "1 Premium Templates",
      showStepRail: "false",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.3,
        mainRatio: 0.55,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "hero",
        speed: "standard",
        stagger: 8,
        countUp: "true",
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "cut", "fade"],
  },
  {
    id: "brand-payoff",
    name: "Brand Payoff",
    category: "cta",
    description: "Centered logo lockup with CTA and URL — minimal outro card.",
    defaultDuration: 90,
    defaultContent: {
      logoText: "SCATTER",
      cta: "Get started today",
      url: "scatter.dev",
      showUrl: "true",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.3,
        mainRatio: 0.55,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "calm",
        stagger: 7,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["cut", "crossfade", "fade"],
  },
  {
    id: "hero-split-text-media",
    name: "Hero Split Text + Media",
    category: "product",
    description: "Split layout with copy rail and product screenshot — primary product intro.",
    defaultDuration: 120,
    defaultContent: {
      headline: "Easy scheduling ahead",
      subhead: "Everything you need to launch faster.",
      body: "",
      media: "",
      cta: "",
      backgroundColor: "",
      accentColor: "",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.35,
        mainRatio: 0.5,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "standard",
        stagger: 10,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "push", "wipe", "mask-reveal"],
  },
  {
    id: "centered-ui-feature",
    name: "Centered UI Feature",
    category: "product",
    description: "Floating UI card on void — explain a single feature with input and CTA.",
    defaultDuration: 120,
    defaultContent: {
      headline: "Create Image",
      body: "Describe what you want to generate.",
      inputText: "A website for my brand",
      cta: "Create",
      uiScreenshot: "",
      showStepRail: "true",
      stepLabel: "1 Premium Templates",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.35,
        mainRatio: 0.5,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "standard",
        stagger: 8,
        typeOn: "true",
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "fade", "mask-reveal"],
  },
  {
    id: "hero-prompt-bar",
    name: "Hero Prompt Bar",
    category: "intro",
    description: "AI/search prompt bar over full-bleed media — hook and product intro.",
    defaultDuration: 105,
    defaultContent: {
      hintText: "First, what are you building?",
      promptText: "I want to create a website for my fashion brand",
      highlightPhrase: "fashion brand",
      backgroundImage: "",
      backgroundColor: "",
      accentColor: "",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.3,
        mainRatio: 0.55,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "hero",
        speed: "standard",
        stagger: 8,
        typeOn: "true",
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "fade", "cut"],
  },
  {
    id: "card-collage-dof",
    name: "Card Collage DOF",
    category: "product",
    description: "Depth-of-field card collage with hero focus and blurred satellites.",
    defaultDuration: 150,
    defaultContent: {
      headline: "",
      stepLabel: "1 Premium Templates",
      "card-1-title": "Project Recap",
      "card-1-body": "",
      "card-2-title": "Q4 Proposal",
      "card-3-title": "Essay Prep",
      heroCardIndex: "1",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.35,
        mainRatio: 0.5,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "standard",
        stagger: 6,
        heroCardIndex: "1",
        blurAmount: 12,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "push", "fade"],
  },
  {
    id: "template-carousel",
    name: "Template Carousel",
    category: "product",
    description: "Focused carousel with dimmed flanks — compare templates or plans.",
    defaultDuration: 150,
    defaultContent: {
      categoryLabel: "1 Premium Templates",
      "item-1-title": "In-House",
      "item-1-meta": "$49",
      "item-2-title": "Freelancer",
      "item-2-meta": "$89",
      "item-3-title": "Agency",
      "item-3-meta": "$149",
      activeIndex: "1",
    },
    defaultMotion: {
      phases: {
        in: "hold",
        main: "hold",
        out: "hold",
        inRatio: 0.25,
        mainRatio: 0.6,
        outRatio: 0.15,
      },
      controls: {
        direction: "up",
        intensity: "standard",
        speed: "standard",
        stagger: 6,
        activeIndex: "1",
        dimOpacity: 0.25,
      },
    },
    supportedFormats: ALL_FORMAT_IDS,
    compatibleTransitions: ["crossfade", "push", "wipe"],
  },
];

export const motionBlockMap = Object.fromEntries(
  motionBlockDefinitions.map((block) => [block.id, block]),
) as Record<string, MotionBlockDefinition>;
